FROM nvcr.io/nvidia/cuda:11.3.0-devel-ubuntu20.04
ARG PYTHON_VERSION=3.8

RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt update
RUN apt install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

RUN DEBIAN_FRONTEND=noninteractive \
    apt update && apt install -y --no-install-recommends tzdata \
    build-essential \
    cmake \
    git \
    curl \
    ca-certificates \
    python3-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

WORKDIR /opt
RUN git clone https://github.com/NVIDIA/apex.git
WORKDIR /opt/apex
RUN git checkout 14ccf5986401104121d0ef286a29386904af3bb7
RUN pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

WORKDIR /opt
RUN git clone https://github.com/NVIDIA/NeMo.git
WORKDIR /opt/NeMo
RUN ./reinstall.sh

WORKDIR /workspace
